apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgat-frontend
  namespace: kgat-frontend
  labels:
    app: kgat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgat-frontend
  template:
    metadata:
      labels:
        app: kgat-frontend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: kgat-frontend
        image: 676206900599.dkr.ecr.ap-northeast-2.amazonaws.com/kgat-frontend:507153b6694dc5999856a790af98f05feb053e82
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kgat-frontend-svc
  namespace: kgat-frontend
spec:
  selector:
    app: kgat-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
